export default {
    "indentation": "2rem",
    "hoverBg": "#e9e9e9",
    "fontSize": "16px",
    "dangerColor": "#a52a2a",
    "actionColor": "#666666",
    "invalidColor": "#ffe3e3",
    "lineHeight": "1.8",
    "lineHeightInput": "1.2rem",
    "inputPadding": "2px 4px",
    "borderRadius": "4px",
    "fontCode": "'Fira Code', 'JetBrains Mono', 'Consolas', 'Liberation Mono', 'Courier New', monospace",
    "iconFontSize": "14px",
    "focusOutline": "1px solid #cccccc",
    "popupHeaderBg": "#107ca7",
    "popupHeaderColor": "#ffffff",
    "popupButtonPrimaryBg": "#107ca7",
    "popupButtonPrimaryColor": "#ffffff",
    "popupButtonBg": "#d9d9d9",
    "popupButtonColor": "#333333",
    "errorBoxBorder-color": "#ffc7c7",
    "errorBoxBg": "#ffe3e3",
    "errorBoxColor": "#a52a2a"
};